routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', function () {
    return view('welcome');
});*/

Auth::routes(); //Las rutas estan en vendor\laravel\framework\src\Illuminate\Routing\Router.php

Route::get('/vue', 'vueController@index')->name('vue');

Route::get('/home', 'HomeController@index')->name('home');

Route::get('/programarSesion', 'Sesiones\ProgramarSesionController@index')->name('programarSesion');

Route::post('/guardarSesion', 'Sesiones\ProgramarSesionController@guardarSesion')->name('guardarSesion');

Route::post('/CambiarContrasena', 'CambiarContrasenaController@updatePassword')->name('CambiarContrasena');

Route::get('seguimientoSesion/consultaSesion', 'Sesiones\SeguimientoSesionController@consultaSesion')->name('seguimientoSesion.consultaSesion');
Route::get('seguimientoSesion/acciones/{id_tsesion}/{id_puntoOrdenDia}/{num_punto}/{bandera}', 'Sesiones\SeguimientoSesionController@acciones')->name('seguimientoSesion.acciones');

Route::get('seguimientoSesion/downloadSoporte/{ruta}', 'Sesiones\SeguimientoSesionController@downloadSoporte')->name('seguimientoSesion.downloadSoporte');

Route::post('seguimientoSesion/editaPunto', 'Sesiones\SeguimientoSesionController@editaPunto')->name('seguimientoSesion.editaPunto');

Route::get('seguimientoSesion/eliminaArchivo/{id_tsoporte}', 'Sesiones\SeguimientoSesionController@eliminaArchivo')->name('seguimientoSesion.eliminaArchivo');

Route::get('seguimientoSesion/liberar', 'Sesiones\SeguimientoSesionController@liberar')->name('seguimientoSesion.liberar'); 

Route::resource('seguimientoSesion', 'Sesiones\SeguimientoSesionController');

Route::get('/generateWordOrdenDia', 'Sesiones\generarWordOrdenDia@createWordDocx')->name('generateWordOrdenDia');

Route::get('EditarSesiones', 'Sesiones\EditarSesionesController@index')->name('EditarSesiones');

Route::post('editarSesion', 'Sesiones\EditarSesionesController@editarSesion')->name('editarSesion');

Route::get('consultarSesion', 'Sesiones\ConsultarSesionesController@index')->name('consultarSesion');

Route::get('consultaSesion/downloadSoporte/{ruta}', 'Sesiones\ConsultarSesionesController@downloadSoporte')->name('consultaSesion.downloadSoporte');

Route::post('acuerdoSesion/capturaAcuerdo', 'Sesiones\AcuerdosSesionController@capturaAcuerdo')->name('acuerdoSesion.capturaAcuerdo');

Route::post('acuerdoSesion/capturaObservacion', 'Sesiones\AcuerdosSesionController@capturaObservacion')->name('acuerdoSesion.capturaObservacion');
Route::post('acuerdoSesion/guardaObservacion', 'Sesiones\AcuerdosSesionController@guardaObservacion')->name('acuerdoSesion.guardaObservacion');

Route::get('acuerdoSesion/liberarMinuta', 'Sesiones\AcuerdosSesionController@liberarMinuta')->name('acuerdoSesion.liberarMinuta');
Route::get('acuerdoSesion/liberarObserva', 'Sesiones\AcuerdosSesionController@liberarObserva')->name('acuerdoSesion.liberarObserva');

Route::resource('acuerdoSesion', 'Sesiones\AcuerdosSesionController');

Route::get('/createMinutaWordDocx', 'Sesiones\createMinutaWordDocx@createMinutaWordDocx')->name('createMinutaWordDocx');
Route::get('/info', 'Sesiones\info@index')->name('info');


Route::post('CerrarSesion', 'Sesiones\EditarSesionesController@CerrarSesion')->name('CerrarSesion');

Route::post('ConsutaSesionFinal', 'Sesiones\ConsultarSesionesController@ConsutaSesionFinal')->name('ConsutaSesionFinal');

Route::post('downloadMinuta', 'Sesiones\ConsultarSesionesController@downloadMinuta')->name('downloadMinuta');

Route::get('comentariosSesion/{id}', 'Sesiones\ComentariosSesionController@index')->name('comentariosSesion');

Route::post('guardaComentarioSesion', 'Sesiones\ComentariosSesionController@guardaComentario')->name('guardaComentarioSesion');

Route::get('eliminaComentarioSesion', 'Sesiones\ComentariosSesionController@eliminaComentario')->name('eliminaComentarioSesion');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/manuales','ManualesController@index')->name('manuales');
Route::get('muestraEnvioApi', 'Sesiones\ConsumoApi@index')->name('muestraEnvioApi');
Route::post('enviaSesionApi', 'Sesiones\ConsumoApi@enviaSesion')->name('enviaSesionApi');
Route::post('buscador', 'Buscador@buscar')->name('buscador');
Route::get('/admUsuarios', 'AdmUsuarios@index')->name('admUsuarios');
Route::get('/usuariosDeshabilitados', 'AdmUsuarios@usuariosDeshabilitadosIndex')->name('usuariosDeshabilitados');
Route::post('/habilitarUsuario', 'AdmUsuarios@habilitarUsuario')->name('habilitarUsuario');
Route::post('/eliminarUsuario', 'AdmUsuarios@eliminarUsuario')->name('eliminarUsuario');
Route::post('/consultaUsuario', 'AdmUsuarios@consultaUsuarios')->name('consultaUsuario');
Route::post('/resetearContrasenia', 'AdmUsuarios@resetearContrasenia')->name('resetearContrasenia');

Route::post('editarUsuario','AdmUsuarios@editarUsuario')->name('editarUsuario');

Route::post('update','AdmUsuarios@update')->name('update');

Route::get('consultar','Sesiones\EditarSesionesController@consultar')->name('consultar');//Consulta de representate 

Route::get('crear','Sesiones\EditarSesionesController@crear')->name('crear');//Crear representate

Route::get('gene','Sesiones\EditarSesionesController@gene')->name('gene');//Devolver datos de crear

// Route::get('editar','Sesiones\EditarSesionesController@editar')->name('editar');//Editar Rrepresentante usuario

Route::get('Eliminar','Sesiones\EditarSesionesController@Eliminar')->name('Eliminar');//Eliminar representate

Route::get('consultapri','Sesiones\EditarSesionesController@consultapri')->name('consultapri');//Usuarios y sus privilegios

Route::get('EditarPrivilegios','Sesiones\EditarSesionesController@EditarPrivilegios')->name('EditarPrivilegios'); // Editar la parte del usuario

Route::get('CrearPri','Sesiones\EditarSesionesController@CrearPri')->name('CrearPri');

Route::get('Insertpri','Sesiones\EditarSesionesController@Insertpri')->name('Insertpri');

Route::get('Updatepri','Sesiones\EditarSesionesController@Updatepri')->name('Updatepri');

Route::get('EliminarPrivilegios','Sesiones\EditarSesionesController@EliminarPrivilegios')->name('EliminarPrivilegios'); //Updatepri

resources/views/AcuerdosSesiones/show.blade.php
@extends('contenedor')
@section('titulo')
<h4>Acuerdos</h4>
@endsection
@section('panel')
    <div id="datosSesion" class="table-responsive">
        <table class="table table-hover">
            <tr>
                <td>Comisión</td>
                <td>No.</td>
                <td>Tipo</td>
                <td>Caracter</td>
                <td>Fecha y Hora de Inicio</td>
                <td>Fecha y Hora de Termino</td>
            </tr>

            @foreach ($datosSesion as $datosSesion)
  
            <tr>
                <td>{{$datosSesion->comision->descripcion}}</td>
                <td>{{$datosSesion->num_sesion."/".$datosSesion->anio_sesion }}</td>
                <td>{{$datosSesion->tipoSesion->descripcion}}</td>
                <td>{{$datosSesion->caracterSesion->descripcion}}</td>
                <td>{{$datosSesion->fecha_programada->format('d-m-Y')." - ".$datosSesion->hora_programada}}</td>
                <td>{{$datosSesion->fecha_programada->format('d-m-Y')." - ".$datosSesion->hora_fin_estimada}}</td>
            </tr>
            
            @endforeach

        </table>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success" >
            {{ $message }}
        </div>
    @endif

    @if ($message = Session::get('error'))
        <div class="alert alert-danger" >
            {{ $message }}
        </div>
    @endif

    <form method="POST" action="{{ route('acuerdoSesion.capturaAcuerdo') }}" enctype="multipart/form-data">                  
        {{ csrf_field() }}
        <div class="row">
            <div class="col-md-1">
                <label>No. Tema:</label>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2" style="float: left">
                <select  name="id_puntoOrdenDia" class="form-control" required>
                    <option value=''>Seleccione una opción</option>
                        @foreach ($listaTemas as $listaTemas)
                            <option value="{{ $listaTemas->id_puntoOrdenDia }}">{{ $listaTemas->numero_punto}}</option> 
                        @endforeach
                </select>
                <input type="hidden" name="id_tsesion" value="{{$datosSesion->id_tsesion}}">
            </div>
            <div class="col-md-3" style="float: left">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-search"></span> Consultar
                </button>
            </div>
    </form>

    <form method="GET" action="{{ route('createMinutaWordDocx') }}">                  
            <div  class="col-md-3" id = "descargar">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-download-alt"></span> Descargar Minuta
                </button>
                <input type="hidden" name="id_tsesion" value="{{$datosSesion->id_tsesion}}">
            </div>
    </form>        
        @if($estatusSesion <= 2 || $estatusSesion >= 4)
            <div  class="col-md-3" id = "Liberar" class="text-right"  style="float: right">
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#Confirmacion">
                    <span class="glyphicon glyphicon-share-alt"></span>Liberar Minuta
                </button>
            </div>
        </div>
        @endif

    <br>
    <br>
    <br>

    @if(!is_null($id_puntoOrdenDia))
        <label>No. Tema: </label>
        {{$datosTema[0]->numero_punto}}
        <br><br>
        <label>Punto: </label>
        {!!nl2br(e($datosTema[0]->punto))!!}
        
        <br><br>
        <form method="POST" action="{{ route('acuerdoSesion.store') }}" enctype="multipart/form-data">                  
            {{ csrf_field() }}
       
         @if(isset($listaObservaciones))
                @foreach ($listaObservaciones as $obs)
                        <label>Observación {{$obs->ponencia->descripcion}}:</label>
                        {{$obs->observacion}}
                        <br><br>
                @endforeach

         @endif


            <br>

            <div class="col-md-12">
                <label>Acuerdo:</label>
                <textarea class="form-control" name="acuerdo" rows="3" value="" required>@if(isset($datosTema[0]->acuerdo->acuerdo)){{$datosTema[0]->acuerdo->acuerdo}}@endif</textarea>
                <input type="hidden" name="id_tsesion" value="{{$datosTema[0]->id_tsesion}}">
                <input type="hidden" name="id_puntoOrdenDia" value="{{$id_puntoOrdenDia}}">
            </div>
            <br><br><br><br><br><br>

    

            <div class="col-md-3">
            <br><br>
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon glyphicon-floppy-disk"></span> Guardar
                </button>
            </div>
        </form>
    @endif

    <!--Modal confirmaciín-->
    <div class="modal fade" id="Confirmacion" role="dialog">
        <div class="modal-dialog modal-dialog-centered modal-sm ">    
        <!-- Contenido-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Liberar</h4>
                </div>
                <form method="GET" action="{{ route('acuerdoSesion.liberarMinuta') }}" enctype="multipart/form-data">
                    <div class="modal-body">                    
                        {{ csrf_field() }}
                        ¿Desea liberar la minuta?
                        <div class="row">
                            <div class="col-md-4">
                                <input type="id_tsesion" name="id_tsesion" value="{{$datosSesion->id_tsesion}}" hidden>
                            </div>
                        </div>
                        <br>
                                             
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">
                            <span class="glyphicon glyphicon-remove"></span> Cancelar
                        </button>
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-share-alt"></span> Liberar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection

resources/views/AcuerdosSesiones/showPonencia.blade.php
@extends('contenedor')
@section('titulo')
<h4>Acuerdos</h4>
@endsection
@section('panel')
    <div id="datosSesion" class="table-responsive">
        <table class="table table-hover">
            <tr>
                <td>Comisión</td>
                <td>No.</td>
                <td>Tipo</td>
                <td>Caracter</td>
                <td>Fecha y Hora de Inicio</td>
                <td>Fecha y Hora de Termino</td>
            </tr>

            @foreach ($datosSesion as $datosSesion)
  
            <tr>
                <td>{{$datosSesion->comision->descripcion}}</td>
                <td>{{$datosSesion->num_sesion."/".$datosSesion->anio_sesion }}</td>
                <td>{{$datosSesion->tipoSesion->descripcion}}</td>
                <td>{{$datosSesion->caracterSesion->descripcion}}</td>
                <td>{{$datosSesion->fecha_programada->format('d-m-Y')." - ".$datosSesion->hora_programada}}</td>
                <td>{{$datosSesion->fecha_programada->format('d-m-Y')." - ".$datosSesion->hora_fin_estimada}}</td>
            </tr>
            
            @endforeach

        </table>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success" >
            {{ $message }}
        </div>
    @endif

    @if ($message = Session::get('error'))
        <div class="alert alert-danger" >
            {{ $message }}
        </div>
    @endif

    <form method="POST" action="{{ route('acuerdoSesion.capturaObservacion') }}" enctype="multipart/form-data">                  
        {{ csrf_field() }}
        <div class="row">
            <div class="col-md-2">
                <label>No. Tema:</label>
            </div>
        </div>

        <div class="row">
            <div class="col-md-2" style="float: left">
                <select  name="id_puntoOrdenDia" class="form-control" required>
                    <option value=''>Seleccione una opción</option>
                        @foreach ($listaTemas as $listaTemas)
                            <option value="{{ $listaTemas->id_puntoOrdenDia }}">{{ $listaTemas->numero_punto}}</option>
                        @endforeach
                </select>
                <input type="hidden" name="id_tsesion" value="{{$datosSesion->id_tsesion}}">
            </div>
            <div class="col-md-3" style="float: left">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-search"></span> Consultar
                </button>
            </div>
    </form>

    <form method="GET" action="{{ route('createMinutaWordDocx') }}">                  
            <div  class="col-md-3" id = "descargar">
                <button type="submit" class="btn btn-success">
                    <span class="glyphicon glyphicon-download-alt"></span> Descargar Minuta
                </button>
                <input type="hidden" name="id_tsesion" value="{{$datosSesion->id_tsesion}}">
            </div>
    </form>        
        @if(($TsesionPonenciaEstatus < 2) && (Auth::user()->id_crol != 3))
            <div  class="col-md-3" id = "Liberar" class="text-right"  style="float: right">
                <button type="button" class="btn btn-success" data-toggle="modal" data-target="#Confirmacion">
                    <span class="glyphicon glyphicon-share-alt"></span>Liberar Observaciones
                </button>
            </div>
        @endif
        </div>
    

    <br>

    @if(!is_null($id_puntoOrdenDia))
        <label>No. Tema: </label>
        {{$datosTema[0]->numero_punto}}
        <br>
        <label>Punto: </label>
        {!!nl2br(e($datosTema[0]->punto))!!}
        <br><br>
        @if($datosTema[0]->numero_punto > 2)<!--Los número de punto 1 y 2 no llevan acuerdo-->
            <label>Acuerdo: </label>
            {{$datosTema[0]->acuerdo->acuerdo}}
        

            <br><br>
            <form method="POST" action="{{ route('acuerdoSesion.guardaObservacion') }}" enctype="multipart/form-data">                  
                {{ csrf_field() }}
                <div class="col-md-12">
                    <label>Observaciones:</label>

                    <textarea class="form-control" name="observacion" rows="3" value="" required>@if(isset($observaciones[0]->observacion)){{$observaciones[0]->observacion}}@endif</textarea> 


                    <input type="hidden" name="id_tsesion" value="{{$datosTema[0]->id_tsesion}}">
                    <input type="hidden" name="id_puntoOrdenDia" value="{{$id_puntoOrdenDia}}">               
                    <input type="hidden" name="id_tacuerdo" value=" {{$datosTema[0]->acuerdo->id_tacuerdo}}">

                </div>
                <br><br><br><br><br><br>
                @if(Auth::user()->id_crol != 3) 
                <div class="col-md-3">
                    <button type="submit" class="btn btn-success">
                        <span class="glyphicon glyphicon glyphicon-floppy-disk"></span> Guardar
                    </button>
                </div>
                @endif
            </form>
        @endif
    @endif

    <!--Modal confirmaciín-->
    <div class="modal fade" id="Confirmacion" role="dialog">
        <div class="modal-dialog modal-dialog-centered modal-sm ">    
        <!-- Contenido-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title">Liberar</h4>
                </div>
                <form method="GET" action="{{ route('acuerdoSesion.liberarObserva') }}" enctype="multipart/form-data">
                    <div class="modal-body">                    
                        {{ csrf_field() }}
                        ¿Desea liberar las observaciones?
                        <div class="row">
                            <div class="col-md-4">
                                <input type="id_tsesion" name="id_tsesion" value="{{$datosSesion->id_tsesion}}" hidden>
                            </div>
                        </div>
                        <br>
                                             
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">
                            <span class="glyphicon glyphicon-remove"></span> Cancelar
                        </button>
                        <button type="submit" class="btn btn-success">
                            <span class="glyphicon glyphicon-share-alt"></span> Liberar
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>

@endsection